# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDBfGCDvbO4QQK6Q4CDMDlyXjtWPj764
"""

name = "NLP Lab"
hours =30
pi = 3.14
topics =["Tokenization","POS tagging","NER"]

if hours > 25:
    print("sufficent hours for learning python.")
else:
    print("Add more practice hours")
for topic in topics:
    print("Learning:", topic)
def greet(student_name):
    return "Welcome to " + student_name
print(greet("AI & NLP Lab"))