# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14g6zzcMw0B-2Zed40vM3CPQIOb0z4BFx
"""

import nltk
from nltk.tokenize import word_tokenize
from nltk.util import ngrams
from nltk.probability import FreqDist

nltk.download('punkt_tab') # Download 'punkt_tab' as suggested by the error

# Sample text
text = "Language modeling is an important part of natural language processing"

# Tokenize words
tokens = word_tokenize(text.lower())

# Create bigrams
bigrams = list(ngrams(tokens, 2))

# Frequency distribution
freq = FreqDist(bigrams)

print("Bigram Frequencies:")
for k, v in freq.items():
    print(k, ":", v)

print("\nMost Common Bigrams:")
print(freq.most_common(5))

import nltk
nltk.download('punkt')

from nltk.tokenize import word_tokenize
from nltk.util import ngrams
from nltk.probability import FreqDist

text = "Natural language processing enables machines to understand human language"

# Tokenization
tokens = word_tokenize(text.lower())

# Unigrams, Bigrams, Trigrams
unigrams = tokens
bigrams = list(ngrams(tokens, 2))
trigrams = list(ngrams(tokens, 3))

print("\nUnigrams:")
print(unigrams)

print("\nBigrams:")
print(bigrams)

print("\nTrigrams:")
print(trigrams)

# Frequency distribution for trigrams
freq_trigrams = FreqDist(trigrams)
print("\nTrigram Frequencies:")
for k, v in freq_trigrams.items():
    print(k, ":", v)

print("\nMost Common Trigrams:")
print(freq_trigrams.most_common(5))